# Site Settings
title: "Arthur Prigent"
description: "Postdoctoral Fellow at ICTP"
url: "https://aprig.github.io"
baseurl: "/arthurprigent"   # Important for project sites

repository: "arthurprigent"

locale: "en-US"
title_separator: "-"
timezone: "Europe/Rome"

# Use Minimal Mistakes theme via remote_theme
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-sitemap


# Social Profiles
author:
  name: "Arthur Prigent"
  avatar: "linkedin_Arthur.png"
  bio: "Postdoctoral Fellow"
  location: "Trieste, Italy"
  googlescholar: "https://scholar.google.com/citations?user=ydKp5rEAAAAJ&hl=fr"
  researchgate: "https://www.researchgate.net/profile/Arthur-Prigent"
  email: "prigent.arthur29@gmail.com"
  github: "aprig"
  linkedin: "https://www.linkedin.com/in/arthur-prigent/"
  orcid: "https://orcid.org/0000-0002-0831-2696"

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  Atools:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge

# Exclude files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - node_modules
  - vendor
  - tmp
  - log
  - .bundle

# Include files
include:
  - .htaccess
  - _pages
  - files

# Optional SEO / Analytics (can configure later)
# analytics:
#   provider: "google-universal"
#   google:
#     tracking_id: "UA-XXXXX-Y"

# Minimal Mistakes Settings
# (you can customize header/footer, logo, nav links, etc. later)
